### PR TITLE
Addproducts

### PR DESCRIPTION
**Pull request by ToxPuro**
This branch became a bit too large, in hindsight I should I have done backend and frontend code in two different branches. 
This branch now has both the frontend page and working backend endpoints integrated. There are some problems in the frontend code, no tests and style could and should be improved. I don't have time for that in this sprint so have to leave it to the next sprint

### CODE REVIEW

**Review by silmish — COMMENTED** [review]
Went through the backend side, cant say much regarding the frontend as not familiar with this tech yet.

**Comment by ilarijn** [comment]
:+1:

No need to push node_modules/ though?

**Review by ilarijn — COMMENTED** [review]
:+1: 

No need to push node_modules/ though?

**Comment by ToxPuro** [comment]
> No need to push node_modules/ though?

Good point, pushed on accident, deleted now

**Pull request merged**
