### PR TITLE
Map view

### PR DESCRIPTION
**Pull request by ilarijn**
A MapPage that tracks Markers currently visible on the Leaflet map using mock data. 

- Clicking on the Marker of a seller opens a SellerPage, the Marker of an event opens an EventPage
    - Different Marker icons can be added later
- MapBottomPanel lists all currently visible events
    - Clicking on the button of an event opens an EventPage
    - No related products listed yet

MapInstance in MapPage.js is required as child of MapContainer to access Leaflet API.

The latest version of react-leaflet required changing browserslist in package.json to: 

"browserslist": [
   ">0.2%",
  "not dead",
  "not op_mini all"
],

### CODE REVIEW

**Review by ToxPuro — APPROVED** [review]
Looks great!
Only thing that comes to mind is that have you looked into how customizable the markers are?
Since currently user can't separate market events from sellers' locations

**Comment by ilarijn** [comment]
> 
> 
> Looks great!
> Only thing that comes to mind is that have you looked into how customizable the markers are?
> Since currently user can't separate market events from sellers' locations


We should be able to replace it with an image or svg through leaflet.Icon. There might even be a way to just draw a circle with text inside with Leaflet, let's see if we can find something

**Comment by NinaKWelch** [comment]
Looking great.

There were some unassigned variables, so maybe check them, in case they will cause an issue when merged.

[https://github.com/ohtu2021satoja/SatojaREKO/pull/33/files](https://github.com/ohtu2021satoja/SatojaREKO/pull/33/files)

**Review by NinaKWelch — APPROVED** [review]

**Comment by ilarijn** [comment]
> 
> 
> Looking great.
> 
> There were some unassigned variables, so maybe check them, in case they will cause an issue when merged.
> 
> https://github.com/ohtu2021satoja/SatojaREKO/pull/33/files

Good call, cleaned up now

**Pull request merged**
